"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { api } from "@/lib/api/client";
import type { Strategy, BacktestDetail, BacktestRunSummary } from "@/lib/api/types";
import { RANGE_TOUCH_PRESET } from "@/components/strategy/StrategyForm";
import { EquityCurve } from "@/components/backtest/EquityCurve";
import { ErrorNotice, Field, money, SOURCES, TIMEFRAMES, WorkspaceHeader } from "@/components/workspace/shared";
export default function BacktestsPage() {
 const [strategies, setStrategies] = useState<Strategy[]>([]), [runs, setRuns] = useState<BacktestRunSummary[]>([]), [strategy, setStrategy] = useState("");
 const [venue, setVenue] = useState("hyperliquid"), [symbol, setSymbol] = useState("BTC/USDC:USDC"), [tf, setTf] = useState("15m"), [capital, setCapital] = useState(10000), [fee, setFee] = useState(.05), [slippage, setSlippage] = useState(.02);
 const date = (days: number) => new Date(Date.now() - days * 86400000).toISOString().slice(0, 10);
 const [start, setStart] = useState(() => date(7)), [end, setEnd] = useState(() => date(0)), [running, setRunning] = useState(false), [error, setError] = useState<unknown>(null), [result, setResult] = useState<BacktestDetail | null>(null);
 useEffect(() => { Promise.all([api.listStrategies(), api.listBacktests()]).then(([s,r]) => { setStrategies(s.data); setRuns(r.data); }).catch(setError); }, []);
 const run = async () => { if(running) return; setRunning(true); setError(null); setResult(null); try { const start_ms = Date.parse(`${start}T00:00:00Z`), end_ms = Date.parse(`${end}T00:00:00Z`); if (!Number.isFinite(start_ms) || !Number.isFinite(end_ms) || start_ms >= end_ms) throw new Error("Choose a start date before the end date."); let sid = strategy; if (!sid) { const { data } = await api.createStrategy({ name: "Confirmed range", payload: RANGE_TOUCH_PRESET }); sid = data.id; setStrategies(p => [...p, data]); setStrategy(sid); } const { data } = await api.runBacktest({ strategy_id: sid, symbol, timeframe: tf, venue, start_ms, end_ms, initial_capital: capital, fee_rate: fee/100, slippage_rate: slippage/100 }); setResult(data); const history = await api.listBacktests(); setRuns(history.data); } catch(e) { setError(e); } finally { setRunning(false); } };
 return <div className="workspace"><WorkspaceHeader eyebrow="TEST THE RULES" title="Turn a setup into evidence." description="Replay your playbook against historical candles from the selected source."><Link className="secondary-button" href="/strategies/new">Edit playbook →</Link></WorkspaceHeader><ErrorNotice error={error} /><div className="settings-grid"><section className="panel settings-panel"><h2>Market & history</h2><div className="settings-fields"><Field label="Price source"><select value={venue} onChange={e => setVenue(e.target.value)}>{SOURCES.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><Field label="Exact market symbol"><input value={symbol} onChange={e => setSymbol(e.target.value)} placeholder="BTC/USDC:USDC" /></Field><Field label="Timeframe"><select value={tf} onChange={e => setTf(e.target.value)}>{TIMEFRAMES.map(t => <option key={t}>{t}</option>)}</select></Field><Field label="Playbook"><select value={strategy} onChange={e => setStrategy(e.target.value)}><option value="">Confirmed range · starting settings</option>{strategies.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><Field label="From · UTC"><input type="date" value={start} onChange={e => setStart(e.target.value)} /></Field><Field label="Until · UTC, exclusive"><input type="date" value={end} onChange={e => setEnd(e.target.value)} /></Field></div></section><section className="panel settings-panel"><h2>Simulation assumptions</h2><div className="settings-fields"><Field label="Starting equity · quote currency"><input type="number" min="1" value={capital} onChange={e => setCapital(Number(e.target.value))} /></Field><Field label="Fee · % per fill"><input type="number" min="0" max="9" step=".01" value={fee} onChange={e => setFee(Number(e.target.value))} /></Field><Field label="Slippage · % per fill"><input type="number" min="0" max="9" step=".01" value={slippage} onChange={e => setSlippage(Number(e.target.value))} /></Field></div><p className="muted" style={{ marginTop: 22 }}>Confirmed-range replay uses 1m, 5m or 15m entries and automatically loads weekly/daily context plus 4H/1H ranges. Confirmation fills at the next open. TP1 closes a partial at midpoint and moves the stop to entry; TP2 exits the rest. Ambiguous bars favor the stop.</p><p className="muted" style={{ marginTop: 10 }}>Up to 5,000 candles per run. Available history varies by source. Includes fees and slippage; excludes funding, liquidation, and order-book liquidity. Drawdown shown is closed-trade equity drawdown.</p><div className="form-actions"><button className="primary-button" disabled={running || !symbol || !start || !end || capital <= 0} onClick={() => void run()}>{running ? "Fetching history & replaying…" : "Run backtest ↗"}</button></div></section></div>
 {result && <><div className="stat-grid" style={{ marginTop: 24 }}>{[["Net P&L", money(result.final_equity-result.initial_capital), "After modeled costs"], ["Completed trades", result.trades.length, "Includes end-of-data exits"], ["Win rate", result.statistics.win_rate == null ? "—" : `${(result.statistics.win_rate*100).toFixed(1)}%`, "Closed trades"], ["Max drawdown", money(result.max_drawdown), "Closed-trade equity"]].map(([label,value,note]) => <div className="stat-card" key={label}><span>{label}</span><strong>{value}</strong><small>{note}</small></div>)}</div><EquityCurve points={result.equity_curve} /><div className="panel scroll-table" style={{ marginTop: 20 }}><table className="backtest-table"><thead><tr><th>Opened</th><th>Direction</th><th>Entry</th><th>Average exit</th><th>Net P&L</th><th>R</th></tr></thead><tbody>{result.trades.map(t => <tr key={t.trade_id}><td>{new Date(t.opened_at_ms).toLocaleString()}</td><td>{t.direction}</td><td>{money(t.entry_price)}</td><td>{money(t.exit_price)}{t.exit_fills?.length ? <details className="muted"><summary>Exit fills · {t.range_timeframe ?? "range"}</summary>{t.exit_fills.map((f,i)=><p key={i}>{f.reason.replaceAll("_"," ")} · {money(f.quantity)} @ {money(f.price)}</p>)}</details> : null}</td><td className={(t.realized_pnl ?? 0)>=0 ? "profit" : "loss"}>{money(t.realized_pnl)}</td><td>{t.realized_r?.toFixed(2) ?? "—"}</td></tr>)}</tbody></table>{!result.trades.length && <div className="empty-workspace"><h2>No completed trades.</h2><p>No setup passed the configured structure, entry, and risk filters in this period.</p></div>}</div></>}
 <section className="panel" style={{ marginTop: 24 }}><div className="panel-toolbar"><h2>Previous runs</h2><span className="muted">Saved with their exact configuration</span></div>{runs.length ? runs.map(r => <button className="event-row" style={{ width: "100%", textAlign: "left" }} key={r.run_id} onClick={async () => { try { const { data } = await api.getBacktest(r.run_id); setResult(data); } catch(e) { setError(e); } }}><span className="event-icon">↗</span><div><strong>{r.symbol} · {r.timeframe}</strong><p>{new Date(r.period_start_ms).toLocaleDateString()} — {new Date(r.period_end_ms).toLocaleDateString()} · {r.total_trades} trades</p></div><b className={`event-time ${r.final_equity>=r.initial_capital ? "profit" : "loss"}`}>{money(r.final_equity-r.initial_capital)}</b></button>) : <div className="empty-workspace"><h2>Your research starts here.</h2><p>Run a backtest to see its trades, costs, and equity curve.</p></div>}</section></div>;
}
