"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { api } from "@/lib/api/client";
import type { Strategy, Watchlist } from "@/lib/api/types";
import type { AlertEvent } from "@/components/workspace/AlertBell";
import { ErrorNotice, Field, human, money, TIMEFRAMES, WorkspaceHeader } from "@/components/workspace/shared";
type Rule = { watchlist_id: string; timeframes: string[]; strategy_id: string | null; enabled: boolean; telegram: boolean; telegram_chat_id: string; last_scan?: number; error?: string };
export default function AlertsPage() {
 const [events, setEvents] = useState<AlertEvent[]>([]), [lists, setLists] = useState<Watchlist[]>([]), [strategies, setStrategies] = useState<Strategy[]>([]), [rules, setRules] = useState<Rule[]>([]);
 const [rule, setRule] = useState<Rule>({ watchlist_id: "", timeframes: ["15m", "1h", "4h", "1d"], strategy_id: null, enabled: true, telegram: false, telegram_chat_id: "" });
 const [telegramReady, setTelegramReady] = useState(false), [browser, setBrowser] = useState(false), [error, setError] = useState<unknown>(null), [saved, setSaved] = useState(false), [saving, setSaving] = useState(false);
 const load = useCallback(async () => { const [e, r] = await Promise.all([api.get<AlertEvent[]>("/alerts"), api.get<{ rules: Rule[]; telegram_configured: boolean }>("/alerts/rules")]); setEvents(e.data); setRules(r.data.rules); setTelegramReady(r.data.telegram_configured); }, []);
 useEffect(() => { void load().catch(setError); Promise.all([api.listWatchlists(), api.listStrategies()]).then(([w, s]) => { setLists(w.data); setStrategies(s.data); }).catch(setError); setBrowser(localStorage.getItem("rt.browserAlerts") === "1"); const t = setInterval(() => void load().catch(setError), 15000); return () => clearInterval(t); }, [load]);
 const choose = (id: string) => { setSaved(false); setRule(rules.find(r => r.watchlist_id === id) ?? { ...rule, watchlist_id: id, enabled: true, telegram: false, telegram_chat_id: "" }); };
 const save = async () => { setSaving(true); setSaved(false); setError(null); try { await api.post("/alerts/rules", rule); await load(); setSaved(true); } catch (e) { setError(e); } finally { setSaving(false); } };
 const notifications = async () => { if (browser) { localStorage.setItem("rt.browserAlerts", "0"); setBrowser(false); return; } if (!("Notification" in window)) { setError(new Error("This browser does not support desktop notifications. In-app and Telegram alerts remain available.")); return; } try { const p = await Notification.requestPermission(); if (p !== "granted") throw new Error("Allow notifications in your browser site settings to enable this channel."); localStorage.setItem("rt.browserAlerts", "1"); setBrowser(true); } catch (e) { setError(e); } };
 return <div className="workspace"><WorkspaceHeader eyebrow="STAY IN THE LOOP" title="Let the market come to you." description="Watch your setups without watching every candle."><button className="secondary-button" onClick={async () => { try { await api.post("/alerts/read"); await load(); } catch(e) { setError(e); } }}>Mark all read</button></WorkspaceHeader><ErrorNotice error={error} />{saved && <div className="notice">Monitor saved. The server will check this watchlist on its next scan.</div>}
 <div className="settings-grid"><section className="panel settings-panel"><h2>Watchlist monitor</h2><p className="muted">Range extremes, confirmed entries, A+ swing failures, held breakouts and no-fade trend warnings. Duplicate events are suppressed.</p><div className="settings-fields"><Field label="Watchlist"><select value={rule.watchlist_id} onChange={e => choose(e.target.value)}><option value="">Choose a watchlist</option>{lists.map(w => <option value={w.id} key={w.id}>{w.name}</option>)}</select></Field><Field label="Playbook"><select value={rule.strategy_id ?? ""} onChange={e => setRule({ ...rule, strategy_id: e.target.value || null })}><option value="">Confirmed range · starting settings</option>{strategies.filter(s => s.active).map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></Field></div><p className="muted" style={{ marginTop: 22 }}>Timeframes</p><div className="chips">{TIMEFRAMES.map(tf => <button key={tf} aria-pressed={rule.timeframes.includes(tf)} className={`chip ${rule.timeframes.includes(tf) ? "selected" : ""}`} onClick={() => setRule({ ...rule, timeframes: rule.timeframes.includes(tf) ? rule.timeframes.filter(t => t !== tf) : [...rule.timeframes, tf] })}>{tf}</button>)}</div><div className="level-row"><span>Monitor enabled</span><input aria-label="Monitor enabled" type="checkbox" checked={rule.enabled} onChange={e => setRule({ ...rule, enabled: e.target.checked })} /></div><div className="form-actions"><button className="primary-button" disabled={saving || !rule.watchlist_id || !rule.timeframes.length} onClick={() => void save()}>{saving ? "Saving…" : "Save monitor"}</button></div><p className="muted" style={{ marginTop: 18 }}>The server must stay running. It pauses 30 seconds between scan cycles; large watchlists and venue rate limits can make cycles longer.</p></section>
 <section className="panel settings-panel"><h2>Your notification channels</h2><div className="level-row"><span>In-app inbox</span><span className="status-pill range">Always on</span></div><div className="level-row"><span>Browser notifications</span><button className="secondary-button" onClick={() => void notifications()}>{browser ? "Disable" : "Enable"}</button></div><p className="muted" style={{ marginTop: 10 }}>Browser alerts need this app open and notification permission. Mobile browser support varies.</p><div className="level-row"><span>Telegram for this monitor</span><input aria-label="Telegram alerts" type="checkbox" checked={rule.telegram} disabled={!telegramReady} onChange={e => setRule({ ...rule, telegram: e.target.checked })} /></div><div style={{ marginTop: 18 }}><Field label="Your Telegram chat ID"><input placeholder="123456789" value={rule.telegram_chat_id} onChange={e => setRule({ ...rule, telegram_chat_id: e.target.value })} /></Field></div><p className="muted" style={{ marginTop: 15 }}>{telegramReady ? "Bot configured. Start a chat with your bot, enter your chat ID, enable Telegram, and save the monitor." : "One-time setup: create a bot with Telegram’s BotFather, set TELEGRAM_BOT_TOKEN in the server environment, then restart the server. The token stays on the server."}</p><a className="muted" href="https://core.telegram.org/bots/tutorial" target="_blank" rel="noreferrer">Telegram bot setup guide ↗</a></section></div>
 {rules.length > 0 && <section className="panel" style={{ marginTop: 24 }}><div className="panel-toolbar"><h2>Saved monitors</h2></div>{rules.map(r => <div className="event-row" key={r.watchlist_id}><span className="live-dot" /><div><strong>{lists.find(w => w.id === r.watchlist_id)?.name ?? "Watchlist"}</strong><p>{r.timeframes.join(" · ")} · {r.enabled ? "Enabled" : "Paused"}</p>{r.error && <p className="loss">{r.error}</p>}</div><div className="event-time"><small>{r.last_scan ? `Last checked ${new Date(r.last_scan).toLocaleTimeString()}` : "Waiting for first scan"}</small><button className="secondary-button" style={{ marginLeft: 12 }} onClick={() => choose(r.watchlist_id)}>Edit</button></div></div>)}</section>}
 <section className="panel" style={{ marginTop: 24 }}><div className="panel-toolbar"><h2>Alert inbox</h2><span className="muted">{events.filter(e => !e.seen).length} unread</span></div>{events.length ? events.map(e => <Link className="event-row" key={e.id} href={`/?symbol=${encodeURIComponent(e.symbol)}&venue=${e.venue}&timeframe=${e.timeframe}${e.strategy_id ? `&strategy_id=${encodeURIComponent(e.strategy_id)}` : ""}`}><span className="event-icon">{e.seen ? "◇" : "◆"}</span><div><strong>{e.symbol} · {e.timeframe}</strong><p>{e.message} · {money(e.price)} · {e.venue}</p></div><div className="event-time"><small>{new Date(e.created_at_ms).toLocaleString()}</small><small>Telegram: {human(e.telegram_status)}</small></div></Link>) : <div className="empty-workspace"><h2>No alerts yet.</h2><p>Save a watchlist monitor above. New setups and market direction changes will appear here.</p><Link className="secondary-button" href="/watchlists">Build a watchlist →</Link></div>}</section></div>;
}
