"use client";
import {api} from "@/lib/api/client";
import type {PairAnalysis} from "@/lib/api/types";
import Link from "next/link";
import { useState, useEffect } from "react";
import { Field } from "@/components/workspace/shared";
export function ManualRange({low, high, onApply, onClear, analysis}: {analysis:PairAnalysis;low?: number; high?: number; onApply: (low:number, high:number)=>void; onClear:()=>void}) {
 const [lo,setLo]=useState(low?.toString() ?? ""), [hi,setHi]=useState(high?.toString() ?? ""), [error,setError]=useState("");
 useEffect(()=>{setLo(low?.toString()??"");setHi(high?.toString()??"");},[low,high]);
 const [notes,setNotes]=useState(""),[reason,setReason]=useState("outer_boundaries"),[busy,setBusy]=useState(false),[saved,setSaved]=useState("");
 async function save(){const l=Number(lo),h=Number(hi);if(!Number.isFinite(l)||!Number.isFinite(h)||l<=0||h<=l){setError("Enter valid high and low prices first.");return;}setBusy(true);setError("");setSaved("");try{await api.post("/observed-ranges",{low:l,high:h,notes,reason,snapshot:analysis});setSaved("Saved privately with the loaded candles and automatic range for comparison.");}catch(e){setError(e instanceof Error?e.message:"Could not save range");}finally{setBusy(false);}}
 return <details className="panel settings-panel" style={{marginBottom:16}} open={low !== undefined}><summary style={{cursor:"pointer"}}>Manual range {low !== undefined ? "· active" : "· set your own boundaries"}</summary><form className="toolbar-controls" style={{marginTop:16,flexWrap:"wrap"}} onSubmit={e=>{e.preventDefault(); const l=Number(lo),h=Number(hi);if(!Number.isFinite(l)||!Number.isFinite(h)||l<=0||h<=l){setError("Enter positive prices with the high above the low.");return;}setError("");onApply(l,h);}}><Field label="Range low"><input type="number" step="any" min="0" required value={lo} onChange={e=>setLo(e.target.value)}/></Field><Field label="Range high"><input type="number" step="any" min="0" required value={hi} onChange={e=>setHi(e.target.value)}/></Field><button className="primary-button">Apply to chart</button><button type="button" className="secondary-button" onClick={()=>{setLo("");setHi("");setError("");onClear();}}>Use automatic range</button></form><div className="settings-fields" style={{marginTop:16}}><Field label="Why these boundaries?"><select value={reason} onChange={e=>setReason(e.target.value)}><option value="outer_boundaries">Outer boundaries</option><option value="internal_consolidation">Internal consolidation</option><option value="support_resistance">Support / resistance</option><option value="reclaim">Reclaimed range</option><option value="other">Other</option></select></Field><Field label="Your reasoning (optional)"><textarea rows={3} maxLength={4000} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Which reactions matter? Why ignore a wick or internal level?"/></Field></div><div className="heading-actions" style={{marginTop:16}}><button type="button" className="primary-button" disabled={busy} onClick={()=>void save()}>{busy?"Saving…":"Save range & context"}</button><Link className="secondary-button" href="/ranges">My saved ranges ↗</Link></div><p role="status">{saved}</p>{error&&<p role="alert">{error}</p>}<p className="muted" style={{marginTop:12}}>Apply previews your levels in this chart URL. Save stores a private example with the current loaded chart context; it does not train or change the engine automatically. Automated scans, alerts and backtests continue using your strategy rules.</p></details>;
}
