"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {api} from "@/lib/api/client";
import type {PairAnalysis} from "@/lib/api/types";
import {TradingChart} from "@/components/dashboard/TradingChart";
import {WorkspaceHeader,human,money} from "@/components/workspace/shared";
type Entry={id:string;low:number;high:number;notes:string;reason:string;symbol:string;venue:string;timeframe:string;created_at_ms:number;asof:number;automatic_low:number|null;automatic_high:number|null};
type Review={groups:{symbol:string;venue:string;timeframe:string;samples:number;evaluation:null|{training_examples:number;held_out_examples:number;baseline_error:number;adjusted_error:number;improves:boolean};median_low_shift:number;median_high_shift:number}[]};
export default function SavedRanges(){
 const [entries,setEntries]=useState<Entry[]>([]),[review,setReview]=useState<Review>({groups:[]}),[selected,setSelected]=useState<(Entry&{snapshot:PairAnalysis})|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
 async function load(){const [a,b]=await Promise.all([api.get<Entry[]>("/observed-ranges"),api.get<Review>("/observed-ranges/review")]);setEntries(a.data);setReview(b.data);}
 useEffect(()=>{load().catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
 async function open(e:Entry){setBusy(true);setError("");try{const {data}=await api.get<Entry&{snapshot:PairAnalysis}>(`/observed-ranges/${e.id}`);setSelected({...e,...data});}catch(e){setError(e instanceof Error?e.message:"Could not open range");}finally{setBusy(false);}}
 async function remove(e:Entry){if(!window.confirm("Delete this saved range and its context permanently?"))return;setBusy(true);try{await api.del(`/observed-ranges/${e.id}`);setSelected(null);await load();}catch(e){setError(e instanceof Error?e.message:"Could not delete range");}finally{setBusy(false);}}
 const snap=selected?.snapshot;
 const overlay:PairAnalysis|null=snap&&selected?{...snap,range:{...snap.range,low:selected.low,high:selected.high,width:selected.high-selected.low,status:"manual",is_tradable:false,metadata:{midpoint:(selected.low+selected.high)/2,structure_confirmed:true}},risk:null,swing_failures:[]}:null;
 return <div className="workspace"><WorkspaceHeader eyebrow="PERSONAL RANGE LIBRARY" title="Your eye for the range." description="Private examples of the boundaries you see, with the chart context preserved at save time."><Link className="primary-button" href="/">Find a market ↗</Link></WorkspaceHeader>{error&&<p role="alert" className="notice error">{error}</p>}
 <details className="panel settings-panel" style={{marginBottom:20}}><summary>Correction review · {entries.length} saved examples</summary><p className="muted" style={{margin:"16px 0"}}>This summarises your corrections; it is not a trained model or a performance claim. Repeated saves of the same market candle count once. Scans, alerts and backtests are unchanged. After 10 distinct observations per group, an experimental offset model learns from the older 70% and is checked against newer markings. Overlapping charts can still bias this check; this measures agreement with your labels, not trading returns.</p>{review.groups.map(g=><div className="level-row" key={`${g.symbol}:${g.venue}:${g.timeframe}`}><span>{g.symbol} · {g.venue} · {g.timeframe} · {g.samples} observations</span><span>{g.evaluation?<small style={{display:"block"}}>Experimental check: {g.evaluation.training_examples} train / {g.evaluation.held_out_examples} held out · error {(g.evaluation.baseline_error*100).toFixed(1)}% → {(g.evaluation.adjusted_error*100).toFixed(1)}% · {g.evaluation.improves?"closer to your markings":"no improvement"}</small>:<small style={{display:"block"}}>Collecting examples · {g.samples}/10 for an experimental check</small>}Median low shift {(g.median_low_shift*100).toFixed(1)}% · high shift {(g.median_high_shift*100).toFixed(1)}%</span></div>)}<small className="muted">Shifts are relative to the automatic range width, not price returns. Positive means a higher level. Groups without automatic bounds are excluded.</small></details>
 {selected&&overlay&&<section style={{marginBottom:24}}><div className="panel settings-panel"><p className="eyebrow">SAVED SNAPSHOT · {selected.symbol} · {selected.venue} · {selected.timeframe}</p><h2>{money(selected.low)} — {money(selected.high)}</h2><p className="muted">Automatic at capture: {money(selected.automatic_low)} — {money(selected.automatic_high)} · saved {new Date(selected.created_at_ms).toLocaleString()}</p><p style={{whiteSpace:"pre-wrap",overflowWrap:"anywhere",margin:"16px 0"}}>{selected.notes||human(selected.reason)}</p><p className="muted">Historical view; may include the candle that was forming when saved. No live entry plan.</p><div className="heading-actions" style={{marginTop:16}}><Link className="secondary-button" href={`/?${new URLSearchParams({symbol:selected.symbol,timeframe:selected.timeframe,venue:selected.venue,range_low:String(selected.low),range_high:String(selected.high)})}`}>Apply to live chart ↗</Link><button className="secondary-button" onClick={()=>setSelected(null)}>Close snapshot</button><button className="secondary-button" disabled={busy} onClick={()=>void remove(selected)}>Delete example</button></div></div><TradingChart key={selected.id} analysis={overlay}/></section>}
 {loading?<p role="status">Loading your examples…</p>:entries.length?<div className="journal-grid">{entries.map(e=><article key={e.id} className="panel journal-card"><p className="eyebrow">{e.symbol} · {e.timeframe} · {e.venue}</p><h2>{money(e.low)} — {money(e.high)}</h2><p>{human(e.reason)}</p><p className="journal-preview">{e.notes||"No additional notes."}</p><p className="muted">Saved {new Date(e.created_at_ms).toLocaleString()}</p><button className="secondary-button" disabled={busy} onClick={()=>void open(e)}>Review saved chart ↗</button></article>)}</div>:<section className="panel journal-empty"><h2>Start with a range you see.</h2><p className="muted">Open a market, expand Manual range, enter your boundaries and choose Save range & context.</p></section>}
 </div>;
}
